# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Deploy to EC2 With Windows

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')


jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Print current directory
      run: echo $(pwd)

    - name: List all files and folders
      run: |
          echo "Listing all files and folders in current directory:"
          dir

    - name: Set up SSH Key
      shell: pwsh
      run: |
         # Create .ssh directory if it doesn't exist
         $sshDir = "$env:USERPROFILE\.ssh"
         if (-not (Test-Path $sshDir)) {
           New-Item -Path $sshDir -ItemType Directory -Force
         }

         # Write the SSH private key from GitHub secret to a file
         $privateKeyPath = "$sshDir\ec2-key.pem"
         $privateKeyContent = "${{ secrets.DEV_SSH_KEY }}"
         $privateKeyContent | Out-File -FilePath $privateKeyPath -Force -Encoding ASCII

         # Set proper permissions on the private key file
         icacls $privateKeyPath /inheritance:r /grant:r "$env:USERNAME:F" /c
         icacls $privateKeyPath /setowner "$env:USERNAME" /c

    - name: Copy file to EC2 using SCP
      shell: bash
      run: |
           echo $($HOME)
           $sshDir = "$env:USERPROFILE\.ssh"
           $privateKeyPath = "$sshDir\ec2-key.pem"
           scp -i "$privateKeyPath" ./deployToIIS.ps1 Administrator@107.26.3.232:C:/GithubTesting
           scp -i "$HOME/.ssh/ec2-key.pem" ./deployToIIS.ps1 Administrator@107.26.3.232:C:/GithubTesting
    
    
    - name: Set up PowerShell session to EC2
      shell: pwsh
      run: |
         $KeyFile = "$env:USERPROFILE\.ssh\ec2-key.pem"
         $EC2User = "Administrator"
         $EC2Host = "107.22.3.238"
         $Password = "${{ secrets.DEV_EC2_PASSWORD }}"  

         try {

           # Create the remote session
          $session = New-PSSession -HostName $EC2Host -UserName $EC2User -KeyFilePath $KeyFile -ErrorAction Stop
          Write-Host "Session created successfully"

         # Upload file to EC2
         Copy-Item -Path '$(pwd)/deployToIIS.ps1' -Destination 'C:/GithubTesting' -ToSession $session
       
          } catch {
            Write-Error "Failed to create session: $_"
          }
          # Close the session
         Remove-PSSession -Session $session

      timeout-minutes: 5  

      env:
        EC2_USER: Administrator
        EC2_HOST: 107.22.3.238
        EC2_KEY: ${{ secrets.DEV_SSH_KEY}}

    - name: Install OpenSSH
      run: |
            Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
            Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
            Start-Service sshd

    - name: Upload PowerShell script to EC2
      run: |
            scp -i $env:DEV_SSH_KEY ./deployToIIS.ps1 Administrator@107.22.3.238:C:/GithubTesting/
      env:
            SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_KEY }}


 

      
